name: Java CI with Gradle

on:
  push:
    branches:
      [- "main" ]
  pull_request:
    branches:
      [- "main" ]

  jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      container: wpilib/roborio-cross-ubuntu:2024-22.04

      steps:
        -name: Checkout repository
         uses: actions/checkout@v4

        -name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
          distribution: 'temurin'
          java-version: '17'

        -name: Cache Gradle dependencies
         uses: actions/cache@v3
         with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore_keys: |
            ${{ runner.os }}-gradle-

        -name: Grant execute permission for Gradle
         run: chmod +x gradlew

        -name: Build robot code
         run: ./gradlew build

        -name: Run WPLib Unit Tests
         run: ./gradlew test
  
  deploy:
    needs: build
    runs-on: [self-hosted] # Use a self-hosted runner on the same network as the robot

    steps:
      -name: Checkout repository
       uses: actions/checkout@v4

      -name: Grant execute permission for Gradle
       run: chmod +x gradlew

      -name: Deploy to Robot
       run: ./gradlew deploy
       env:
        TEAM_NUMBER: "4295" # Replace with your FRC team number

      -name: Reboot roboRIO
       run: ssh -o StrictHostKeyChecking=no lvuser@roborio-4295-FRC.local "sudo reboot"
       env:
        SSH_AUTH_SOCK: /temp/ssh_agent.sock