name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Robot-Code/**'
      - 'Middleware-Code/**'
      - 'Vision-Code/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'Robot-Code/**'
      - 'Middleware-Code/**'
      - 'Vision-Code/**'

jobs:
  build-middleware:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Middleware-Code')
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0
    - name: Build Middleware with Gradle Wrapper
      run: cd Middleware-Code && ./gradlew build

  build-robot:
    runs-on: ubuntu-latest
    needs: build-middleware
    if: contains(github.event.head_commit.message, 'Robot-Code')
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0
    - name: Build Robot Code with Gradle Wrapper
      run: cd Robot-Code && ./gradlew build

  build-vision:
    runs-on: ubuntu-latest
    needs: build-middleware
    if: contains(github.event.head_commit.message, 'Vision-Code')
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0
    - name: Build Vision Code with Gradle Wrapper
      run: cd Vision-Code && ./gradlew build
