on:
    workflow_dispatch:
      inputs:
        releaseVersion:
          description: "Release version number"
          type: string
          required: true
  
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      releaseVersion: ${{ inputs.releaseVersion }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Clone lib branch
        run: |
          gh repo clone HeliosMoros/FRC_Reefscape_vson-Swrv -- -b FRC_Team4295Drive&Vision
          cd FRC_Reefscape_vson-Swrv
          gh workflow run update.yml -f releaseVersion=${{ inputs.releaseVersion }}